"""Add direct stock plans

Revision ID: 04940a50fc6b
Revises: 442e83163d3a
Create Date: 2023-08-16 13:20:59.699164

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '04940a50fc6b'
down_revision = '442e83163d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direct_stocks_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=True),
    sa.Column('stock_currency', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('direct_stocks_plan')
    # ### end Alembic commands ###
