"""Rename RSUPlan column to approval_date

Revision ID: 0f6517250d4a
Revises: 8b959405f629
Create Date: 2023-07-02 12:11:33.323560

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0f6517250d4a'
down_revision = '8b959405f629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rsu_plans', schema=None) as batch_op:
        batch_op.alter_column('grant_date', new_column_name='approval_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rsu_plans', schema=None) as batch_op:
        batch_op.alter_column('approval_date', new_column_name='grant_date')

    # ### end Alembic commands ###
