"""add is_deleted field to projects

Revision ID: 2126ef7ea728
Revises: 5649893ed72f
Create Date: 2025-12-24 17:29:59.069586

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2126ef7ea728'
down_revision = '5649893ed72f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
    # ### end Alembic commands ###
