"""Re-create directstocks tables

Revision ID: 3f01520aad12
Revises: ca3aea0fb58e
Create Date: 2023-08-16 15:48:18.971315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f01520aad12'
down_revision = 'ca3aea0fb58e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direct_stocks_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=True),
    sa.Column('stock_currency', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('direct_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direct_stocks_plan_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('acquisition_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['direct_stocks_plan_id'], ['direct_stocks_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('direct_stocks')
    op.drop_table('direct_stocks_plan')
    # ### end Alembic commands ###
