"""Remove unused table StockOptions

Revision ID: 442e83163d3a
Revises: 3c73c602245f
Create Date: 2023-08-08 09:25:07.958716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442e83163d3a'
down_revision = '3c73c602245f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_options')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_options',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('taxpayer_owner', sa.INTEGER(), nullable=True),
    sa.Column('grant_date', sa.DATE(), nullable=True),
    sa.Column('symbol', sa.VARCHAR(length=16), nullable=True),
    sa.Column('stock_currency', sa.VARCHAR(length=3), nullable=True),
    sa.Column('strike_price', sa.FLOAT(), nullable=True),
    sa.Column('strike_price_currency', sa.VARCHAR(length=3), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
