"""Introducing tax_statements

Revision ID: 467943ee26c7
Revises: a0de7c83776f
Create Date: 2021-12-10 15:33:00.017960

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '467943ee26c7'
down_revision = 'a0de7c83776f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('income_1', sa.Integer(), nullable=True),
    sa.Column('income_2', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('income_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['income_id'], ['income_segments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_statements')
    op.drop_table('income_segments')
    # ### end Alembic commands ###
