"""Adding field 7CF (PME investment)

Revision ID: 65a6a9a7fe2d
Revises: a0d37ef1690e
Create Date: 2022-04-28 16:34:44.427849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65a6a9a7fe2d'
down_revision = 'a0d37ef1690e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otherinvestments_segments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pme_capital_subscription_7CF', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otherinvestments_segments', schema=None) as batch_op:
        batch_op.drop_column('pme_capital_subscription_7CF')

    # ### end Alembic commands ###
