"""Remove direct stocks table before re-creating it

Revision ID: 8f82b83eb20e
Revises: 04940a50fc6b
Create Date: 2023-08-16 13:46:57.201684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f82b83eb20e'
down_revision = '04940a50fc6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('direct_stocks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direct_stocks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('symbol', sa.VARCHAR(length=16), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('acquisition_date', sa.DATE(), nullable=True),
    sa.Column('acquisition_price', sa.FLOAT(), nullable=True),
    sa.Column('stock_currency', sa.VARCHAR(length=3), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
