"""Adding stock sales related table

Revision ID: 9045de055e80
Revises: cd0501192701
Create Date: 2022-04-25 16:29:46.465036

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9045de055e80'
down_revision = 'cd0501192701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direct_stocks_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('sell_date', sa.Date(), nullable=True),
    sa.Column('sell_price', sa.Float(), nullable=True),
    sa.Column('sell_currency', sa.String(length=3), nullable=True),
    sa.Column('fees', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('direct_stocks_sales')
    # ### end Alembic commands ###
