"""Re-create direct stocks to point to direct stocks plans

Revision ID: 963839c51c5e
Revises: 8f82b83eb20e
Create Date: 2023-08-16 13:47:36.485831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963839c51c5e'
down_revision = '8f82b83eb20e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direct_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direct_stocks_plan_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('acquisition_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['direct_stocks_plan_id'], ['direct_stocks_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('direct_stocks')
    # ### end Alembic commands ###
