"""Adding reductions and shareholding segments

Revision ID: a2e04ac263d6
Revises: b8bc26dc7ed2
Create Date: 2022-04-01 15:36:55.082479

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a2e04ac263d6'
down_revision = 'b8bc26dc7ed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otherinvestments_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pme_capital_subscription_7CH', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicecharges_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('children_daycare_fees_7GA', sa.Integer(), nullable=True),
    sa.Column('home_services_7DB', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shareholding_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taxable_acquisition_gain_1TZ', sa.Integer(), nullable=True),
    sa.Column('acquisition_gain_rebates_1UZ', sa.Integer(), nullable=True),
    sa.Column('acquisition_gain_50p_rebates_1WZ', sa.Integer(), nullable=True),
    sa.Column('exercise_gain_1_1TT', sa.Integer(), nullable=True),
    sa.Column('exercise_gain_2_1UT', sa.Integer(), nullable=True),
    sa.Column('capital_gain_3VG', sa.Integer(), nullable=True),
    sa.Column('capital_loss_3VH', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_statements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servicecharges_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('otherinvestments_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shareholding_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_servicecharges_to_statement", 'servicecharges_segments', ['servicecharges_id'], ['id'])
        batch_op.create_foreign_key("fk_shareholding_to_statement", 'shareholding_segments', ['shareholding_id'], ['id'])
        batch_op.create_foreign_key("fk_otherinvestments_to_statement", 'otherinvestments_segments', ['otherinvestments_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_statements', schema=None) as batch_op:
        batch_op.drop_constraint("fk_servicecharges_to_statement", type_='foreignkey')
        batch_op.drop_constraint("fk_shareholding_to_statement", type_='foreignkey')
        batch_op.drop_constraint("fk_otherinvestments_to_statement", type_='foreignkey')
        batch_op.drop_column('shareholding_id')
        batch_op.drop_column('otherinvestments_id')
        batch_op.drop_column('servicecharges_id')

    op.drop_table('shareholding_segments')
    op.drop_table('servicecharges_segments')
    op.drop_table('otherinvestments_segments')
    # ### end Alembic commands ###
