"""Adding fixed income investments

Revision ID: a7c6de4ed921
Revises: 560e06dc062c
Create Date: 2022-04-29 10:26:51.922993

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a7c6de4ed921'
down_revision = '560e06dc062c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixedincomeinvestment_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixed_income_interests_2TR', sa.Integer(), nullable=True),
    sa.Column('fixed_income_interests_already_taxed_2BH', sa.Integer(), nullable=True),
    sa.Column('interest_tax_already_paid_2CK', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_statements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fixedincomeinvestment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_fixedincomeinvestment_to_statement", 'fixedincomeinvestment_segments', ['fixedincomeinvestment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_statements', schema=None) as batch_op:
        batch_op.drop_constraint("fk_fixedincomeinvestment_to_statement", type_='foreignkey')
        batch_op.drop_column('fixedincomeinvestment_id')

    op.drop_table('fixedincomeinvestment_segments')
    # ### end Alembic commands ###
