"""Remove directstocks tables before re-creating it

Revision ID: ca3aea0fb58e
Revises: 963839c51c5e
Create Date: 2023-08-16 15:47:32.395348

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ca3aea0fb58e'
down_revision = '963839c51c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('direct_stocks')
    op.drop_table('direct_stocks_plan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direct_stocks_plan',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=256), nullable=True),
    sa.Column('symbol', sa.VARCHAR(length=16), nullable=True),
    sa.Column('stock_currency', sa.VARCHAR(length=3), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('direct_stocks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('direct_stocks_plan_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('acquisition_date', sa.DATE(), nullable=True),
    sa.Column('acquisition_price', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['direct_stocks_plan_id'], ['direct_stocks_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
