"""Adding stock-related tables

Revision ID: cd0501192701
Revises: a2e04ac263d6
Create Date: 2022-04-22 13:01:11.571975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd0501192701'
down_revision = 'a2e04ac263d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direct_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('taxpayer_owner', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('acquisition_price', sa.Float(), nullable=True),
    sa.Column('stock_currency', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rsu_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('taxpayer_owner', sa.Integer(), nullable=True),
    sa.Column('grant_date', sa.Date(), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=True),
    sa.Column('stock_currency', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stock_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('taxpayer_owner', sa.Integer(), nullable=True),
    sa.Column('grant_date', sa.Date(), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=True),
    sa.Column('stock_currency', sa.String(length=3), nullable=True),
    sa.Column('strike_price', sa.Float(), nullable=True),
    sa.Column('strike_price_currency', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rsu_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rsu_plan_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('vesting_date', sa.Date(), nullable=True),
    sa.Column('acquisition_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['rsu_plan_id'], ['rsu_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rsu_stocks')
    op.drop_table('stock_options')
    op.drop_table('rsu_plans')
    op.drop_table('direct_stocks')
    # ### end Alembic commands ###
