"""Adding StockOption Plan and Vestings

Revision ID: ffa8aecac3d7
Revises: b8de5c784430
Create Date: 2023-07-25 10:26:02.644585

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ffa8aecac3d7'
down_revision = 'b8de5c784430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stockoption_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('taxpayer_owner', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=True),
    sa.Column('stock_currency', sa.String(length=3), nullable=True),
    sa.Column('strike_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stockoption_vestings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stockoption_plan_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('vesting_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['stockoption_plan_id'], ['stockoption_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stockoption_vestings')
    op.drop_table('stockoption_plans')
    # ### end Alembic commands ###
